Repository mohitmishra786/hacktoberfest-2022, pull requests merged in 2022-10, with the labels that each got.

#4 Added 3 folders named codechef, codeforces, kickstart in the competitive for the issue #3
  Competitive Coding/CodeForces/A_Next_Round.cpp
  Competitive Coding/CodeForces/A_Next_Round.exe
  Competitive Coding/CodeForces/A_Suffix_Array_-_1.cpp
  Competitive Coding/CodeForces/A_Team.cpp
  Competitive Coding/CodeForces/A_Theatre_Square.cpp
  Competitive Coding/CodeForces/A_Two_Elevators.cpp
  Competitive Coding/CodeForces/A_Watermelon.cpp
  Competitive Coding/CodeForces/A_Way_Too_Long_Words.cpp
  Competitive Coding/CodeForces/Codeforces-1722.cpp
  Competitive Coding/Codechef/Copy_and_Paste.cpp
  Competitive Coding/Codechef/Dazzling_AXNODR_Challenge.cpp
  Competitive Coding/Codechef/Dazzling_GCD_Pair.cpp
  Competitive Coding/Codechef/Enormous_Input_Test.cpp
  Competitive Coding/Codechef/Ezio_and_Guards.cpp
  Competitive Coding/Codechef/Find_Remainder.cpp
  Competitive Coding/Codechef/Id_and_Ship.cpp
  Competitive Coding/Codechef/Lucky_Four.cpp
  Competitive Coding/Codechef/Make_all_equal_using_Pairs.cpp
  Competitive Coding/Codechef/Number_Mirror.cpp
  Competitive Coding/Codechef/The_Cooler_Dilemma_1.cpp
  Competitive Coding/Codechef/The_Cooler_Dilemma_2.cpp
  Competitive Coding/Codechef/Valid_Triangles.cpp
  Competitive Coding/Codechef/olympic_ranking.cpp
  Competitive Coding/Codechef/olympic_ranking.exe
  Competitive Coding/Kickstart/Challenge_Nine.cpp
  Competitive Coding/Kickstart/Challenge_Nine.exe
  Competitive Coding/Kickstart/Coloring_Game.cpp
  Competitive Coding/Kickstart/Record_Breaker.cpp
  Competitive Coding/Kickstart/Sample_Problem.cpp
  Competitive Coding/Kickstart/Speed_Typing.cpp
  Competitive Coding/Kickstart/Wiggle_Walk.cpp
  Competitive Coding/Kickstart/Wiggle_Walk.exe
  Competitive Coding/Kickstart/test.exe
Labels: hacktoberfest, hacktoberfest-accepted

#5 Created average-binary-tree-levels.cpp
  Competitive Coding/Codechef/average-binary-tree-levels.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#6 Added implementation of various ML Algorithms
  ML/KMeansClustering.ipynb
  ML/LinearRegression.ipynb
  ML/PCA.ipynb
  ML/Readme.md
Labels: hacktoberfest, hacktoberfest-accepted

#23 Added climbing stairs problem dynamic programming solution
  Competitive Coding/Codechef/climbingStairs.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#26 fibonacci number dynamic programming solution
  Competitive Coding/Codechef/fibonacciNum.cpp
  Competitive Coding/Kickstart/inorderTraversal.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#35 Create Subarray_with_givensum.cpp
  Competitive Coding/* A simple program to print subarray with sum as given sum */#include <bits/stdc++.h> using namespace std;/* Returns true if the there is a subarray of arr[] with sum equal to 'sum' otherwise returns false. Also, prints the result */void subArraySum(int arr[], int n, int sum) {/Pick a starting point  for (int i = 0; i < n; i++) {   int currentSum = arr[i];    if (currentSum == sum) {    cout << "Sum found at indexes " << i << endl;    return;   }   else {/Try all subarrays starting with 'i'    for (int j = i + 1; j < n; j++) {     currentSum += arr[j];      if (currentSum == sum) {      cout << "Sum found between indexes "       << i << " and " << j << endl;      return;     }    }   }  }  cout << "No subarray found";  return; }/Driver Code int main() {  int arr[] = { 15, 2, 4, 8, 9, 5, 10, 23 };  int n = sizeof(arr)/sizeof(arr[0]);  int sum = 23;  subArraySum(arr, n, sum);  return 0; }/This code is contributed/Subarray_with_givensum.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#44 Largest and smallest number in an array
  Competitive Coding/Largest_and_smallest_number_in_an_unsorted_array.c++
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#45 Removing Duplicates from an Array
  Competitive Coding/Removing Duplicate from an Array.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#49 Create reverse_an_array.cpp
  Competitive Coding/reverse_an_array.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#51 Create primeNumber.js
  Competitive Coding/primeNumber.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#58 Create 1000A.Codehorses T-Shirt.cpp
  Competitive Coding/CodeForces/1000A.Codehorses T-Shirt.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#64 created reverse_a_linkedlist.cpp
  Competitive Coding/reverse_a_linkedlist.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#63 Added the program to count the number of vowels in the string.
  Competitive Coding/count_vowels.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#65 Added #61
  Competitive Coding/find_leaf.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#76 Create count_leafnodes.cpp
  Competitive Coding/count_leafnodes.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#77 Create radix_sort.py
  Competitive Coding/radix_sort.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#78 palindrome program added
  Competitive Coding/palindrome_C.c
  Competitive Coding/palindrome_python.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#84 Create postOrder_without_recursion.java
  postOrder_without_recursion.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#83 How do you reverse words in a given sentence without using any library method? based on issue #42
  Competitive Coding/RevWords.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#82 Created a file to find out length of a linked list.
  Competitive Coding/Length-Linked-List.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#91 Added find all permutations of a string in Python
  Competitive Coding/permutations_of_string.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#93 added swap using c
  Competitive Coding/swap.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#99 Revert "Added find all permutations of a string in Java"
  Competitive Coding/permutations_of_string.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#98 Impelmented Binary search in JS
  Competitive Coding/Binary_search.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#96 Create Inorder traversal in binary tree
  Competitive Coding/How do you print all nodes of a given binary tree using inorder traversal without recursion?
  Competitive Coding/Inorder traversal in binary tree
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#95 Added Palindrome in Java
  Competitive Coding/palindrome_java.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#101 Create String_reversal_using_recursion.cpp
  Competitive Coding/String_reversal_using_recursion.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#100 Create Longest-Palindromic-Substring.py
  Competitive Coding/Longest-Palindromic-Substring.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#102 Create countofgivencharacter.py
  Competitive Coding/countofgivencharacter.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#110 Added Remove duplicate array in java
  Competitive Coding/.idea/.gitignore
  Competitive Coding/.idea/Competitive Coding.iml
  Competitive Coding/.idea/misc.xml
  Competitive Coding/.idea/modules.xml
  Competitive Coding/.idea/vcs.xml
  Competitive Coding/RemoveDuplicateInArray.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#108 create leetcode
  Competitive Coding/leetcode
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#107 Created a function to merge two sorted arrays
  Competitive Coding/mergeSortedArrays.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#106 Create snake.cpp
  README.md
  snake.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#105 Insurance Project
  ML/reg+ranom forest/eda-regression.ipynb
  ML/reg+ranom forest/insurance.csv
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#104 Merge Sort in python
  mergesort.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#103 Create Banking System App
  Banking System App
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#111 GuessTheNumber
  Competitive Coding/GuessTheNumber.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#114 DigitClassification
  ML/DigitClassification.ipynb
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#115 Created shellSort.java
  shellSort.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#117 Create Inorder Tree Traversal without recursion and without stack
  Competitive Coding/Inorder Tree Traversal without recursion and without stack
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#116 Level Order Traversal of BST
  Competitive Coding/Level Order Traversal of BST.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#118 Iterative Quicksort Algorithm
  Competitive Coding/iterative_quicksort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#121 ok
  binary tree
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#120 Create minm_element_of_array.cpp
  cpp/minm_element_of_array.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#119 Check Palindrome
  cpp/check-palindrome.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#127 Create Data_Structures_Definition.md
  Competitive Coding/Data_Structures_Definition.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#126 Add files via upload
  PreOrder_Traversal_of_Binary_Tree.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#125 Cousins of Binary Tree
  Competitive Coding/cousinsBinaryTree.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#123 submitted ..what is an integer array? #88
  Interger Arrays in Cpp.docx
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#132 Create Longest Palindromic Substring.py
  Competitive Coding/Longest Palindromic Substring.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#131 Create RemoveEveryOtherItem.cpp
  Competitive Coding/Binarysearch.cpp
  Competitive Coding/RemoveEveryOtherItem.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#138 Implemented binary search in c++ that resolves #52
  binarySearch
  binarySearch.cpp
  minOrMaxElement
  minOrMaxElement.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#135 Implemented counting sort algorithm in c++ (resolves #71)
  Sorting/countingSort
  Sorting/countingSort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#134 added Next Round problem in python
  Competitive Coding/CodeForces/Next_Round.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#139 Added ML project
  ML/Handwritten-Digit-Recognition-Project/GUI.ipynb
  ML/Handwritten-Digit-Recognition-Project/ML_Final (1).ipynb
  ML/Handwritten-Digit-Recognition-Project/README.md
  ML/Handwritten-Digit-Recognition-Project/Screenshots/0.png
  ML/Handwritten-Digit-Recognition-Project/Screenshots/1.png
  ML/Handwritten-Digit-Recognition-Project/Screenshots/2.png
  ML/Handwritten-Digit-Recognition-Project/Screenshots/3.png
  ML/Handwritten-Digit-Recognition-Project/Screenshots/4.png
  ML/Handwritten-Digit-Recognition-Project/Screenshots/5.png
  ML/Handwritten-Digit-Recognition-Project/Screenshots/6.png
  ML/Handwritten-Digit-Recognition-Project/Screenshots/7.png
  ML/Handwritten-Digit-Recognition-Project/Screenshots/8.png
  ML/Handwritten-Digit-Recognition-Project/Screenshots/9.png
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#140 Code to Generate QR Code in Python
  Generate_qr_code.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#142 Create TheCheaperCab.cpp
  Competitive Coding/Codechef/TheCheaperCab.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#150 Create bubblesort.cpp
  Sorting/bubblesort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#149 Implemented sorting and searching algorithms in CPP
  cpp/Searching Algorithms/BinarySearch.cpp
  cpp/Searching Algorithms/LinearSearch.cpp
  cpp/Sorting Algorithms/BubbleSort.cpp
  cpp/Sorting Algorithms/InsertionSort.cpp
  cpp/Sorting Algorithms/MergeSort.cpp
  cpp/Sorting Algorithms/QuickSort.cpp
  cpp/Sorting Algorithms/SelectionSort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#148 Added , Remove duplicates from sorted array
  Remove duplicates from sorted array
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#147 Added , What steps would you take to find the missing number in an integer array.
  What steps would you take to find the missing number in an integer array?
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#146 Added a new file Huffman code in python
  Competitive Coding/Huffman_coding.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#158 Number Guessing Game in Java
  num_guess.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#157 Added "Interpolation Search"
  cpp/Searching Algorithms/InterpolationSearch.cpp
  cpp/Sorting Algorithms/HeapSort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#156 Create Binarytree
  Binarytree
  management system library
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#154 Added Linklist.py
  Linklist.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#162 Create DjikstrasShortestPath.cpp
  Competitive Coding/DjikstrasShortestPath.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#161 Create random_password_generator.py
  random_password_generator.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#159 Djikstra Algorithm included and all files are fixed
  Competitive Coding/Codechef/climbingStairs.cpp
  Competitive Coding/Codechef/fibonacciNum.cpp
  Competitive Coding/How do you print all nodes of a given binary tree using inorder traversal without recursion?
  Competitive Coding/Kickstart/inorderTraversal.cpp
  Competitive Coding/Removing Duplicate from an Array.cpp
  Competitive Coding/palindrome_C.c
  Competitive Coding/palindrome_python.py
  Game Development/GalaxyGame/README.md
  ML/reg+ranom forest/insurance.csv
  PreOrder_Traversal_of_Binary_Tree.cpp
  Sorting/countingSort
  What steps would you take to find the missing number in an integer array?
  binarySearch
  cpp/DJIKSTRA Algorithm.cpp
  cpp/Searching Algorithms/BinarySearch.cpp
  cpp/Searching Algorithms/InterpolationSearch.cpp
  cpp/Searching Algorithms/LinearSearch.cpp
  cpp/Sorting Algorithms/BubbleSort.cpp
  cpp/Sorting Algorithms/HeapSort.cpp
  cpp/Sorting Algorithms/InsertionSort.cpp
  cpp/Sorting Algorithms/MergeSort.cpp
  cpp/Sorting Algorithms/QuickSort.cpp
  cpp/Sorting Algorithms/SelectionSort.cpp
  cpp/check-palindrome.cpp
  mergesort.py
  minOrMaxElement
  num_guess.java
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#164 Hangman Game in python
  Hangman in Python.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#168 Create How are duplicate nodes removed in an unsorted linked list
  How are duplicate nodes removed in an unsorted linked list
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#167 Create how is a merge sort algorithm impelmented
  how is a merge sort algorithm impelmented
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#165 Create Remove duplicates from sorted array 2
  Remove duplicates from sorted array 2
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#174 Create snake-water-gun.py
  snake-water-gun.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#173 Zig-Zag Level Order Traversal cpp solution
  Competitive Coding/Zig-Zag Level Order Traversal
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#172 Super-mart management system
  Super-mart management system
  coffeeshop.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#171 Create WordBoggle.cpp
  Competitive Coding/WordBoggle.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#170 Create Coffee Machine.py
  Coffee Machine.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#169 Create BucketSort.cpp
  Sorting/BucketSort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#181 Music player in python
  music_player.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#180 Create CycleSortJava
  Sorting/CycleSortJava
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#179 Added C++ Codes in Respective Folder
  cpp/Binary to Decimal Converter.cpp
  cpp/Counting Sort.cpp
  cpp/Doubly Linked List.cpp
  cpp/FREQUENCY.cpp
  cpp/Graph Coloring.cpp
  cpp/Heap Sort.cpp
  cpp/Infix to Postfix Stack.cpp
  cpp/Insertion Sort.cpp
  cpp/LCASE.cpp
  cpp/Merge Sort.cpp
  cpp/Odd Even Sort.cpp
  cpp/Password Generator.cpp
  cpp/cube.cpp
  cpp/cubehole.cpp
  cpp/diamond.cpp
  cpp/exp1.cpp
  cpp/factorial.cpp
  cpp/gcd.cpp
  cpp/ltriangle.cpp
  cpp/luckynumber.cpp
  cpp/permitation.cpp
  cpp/power_of_number.cpp
  cpp/prime.cpp
  cpp/print_matrix.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#178 added codechef solutions
  Competitive Coding/Codechef/GCD_operations.cpp
  Competitive Coding/Codechef/Little_Elephant_and_Candies.cpp
  Competitive Coding/Codechef/Root_the_Tree.cpp
  Competitive Coding/Codechef/Task_Times.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#176 Word break
  cpp/word_break.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-fest

#175 Added Peak_Element_Array.cpp
  Competitive Coding/cpp codes/Peak_Element_Array.cpp
Labels: hacktoberfest, hacktober-fest
